image: docker:dind

variables:
  PROJECT: "agents-apigee"

  # Fortify
  FORTIFY_PROJECT: "10716"
  FORTIFY_BUILD_ID: "agents-apigee"
  FORTIFY_INCLUDE: "**/*.go"
  FORTIFY_EXCLUDE: "**/*_test.go"

  # Blackduck
  BLACKDUCK_PROJECT_NAME: "Amplify - APIC Apigee Edge Agents"

  #  SRM
  SRM_PROJECT_NAME: "${BLACKDUCK_PROJECT_NAME}"
  SRM_PROJECT_ID: "228"

  # these needed for go workspace
  GOWORK: ${CI_PROJECT_DIR}/go.work
  GOFLAGS: "-mod=readonly"

########################################
# set up custom names for the pipelines of releases and nightly schedules
########################################
  PIPELINE_NAME: "$CI_COMMIT_MESSAGE"

workflow:
  name: "$PIPELINE_NAME"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $COMPONENT_TESTS_ONLY == "y"
      variables:
        PIPELINE_NAME: "Scheduled nightly tests"
    - if: $CI_PIPELINE_SOURCE == "schedule" && $VERSION == "SNAPSHOT"
      variables:
        PIPELINE_NAME: "Scheduled nightly SecurityCI default branch"
    - if: $CI_PIPELINE_SOURCE == "schedule" && $VERSION == "LATEST"
      variables:
        PIPELINE_NAME: "Scheduled nightly SecurityCI on LATEST"
    - when: always

include:
  - project: "apigov/gitlabci"
    ref: master
    file: "/.gitlab-ci-sonar.yml"
  - project: "apigov/beano_cicd"
    ref: $BEANO_CICD_GREEN
    # the order of these include files is important
    file:
      - "/gitlabci/variables.yml"
      - "/gitlabci/restrictions.yml"
      - "/gitlabci/jobs.yml"
  - project: "scurity/gitlabci"
    ref: $SCURITY_GREEN
    file:
      - "/.gitlab-ci-fortify.yml"
      - "/.gitlab-ci-twistlock.yml"
      - "/.gitlab-ci-iriusrisk.yml"
      - "/.gitlab-ci-blackduck.yml"
      - "/.gitlab-ci-security.yml"
  - project: "apigov/beano_cicd"
    ref: $BEANO_CICD_GREEN
    # the order of these include files is important
    file:
      - "/gitlabci/securityjobs.yml"
      - "/gitlabci/securityjobsformirror.yml"

stages:
  - test
  - qa-test
  - sonar-preview
  - sonar-publish
  - security-scans
  - security-review

twistlock-discovery:
  rules:
    - !reference [.beano-security-snapshot-rules, rules]
  before_script:
    - apk --no-cache update && apk add make
    - cd discovery && make docker-build
    - export IMAGE_NAME=apigee-discovery-agent:latest
    - cd ..
    - echo "TL_DA=true" >> build.env

twistlock-traceability:
  rules:
    - !reference [.beano-security-snapshot-rules, rules]
  before_script:
    - apk --no-cache update && apk add make
    - cd traceability && make docker-build
    - export IMAGE_NAME=apigee-traceability-agent:latest
    - cd ..
    - echo "TL_TA=true" >> build.env

twistlock-discovery:on-schedule:
  variables:
    AGENT_NAME: "apigee_discovery_agent"

twistlock-traceability:on-schedule:
  variables:
    AGENT_NAME: "apigee_traceability_agent"
