image: docker:dind

variables:
  PROJECT: 'agents-apigee'
  
  # Fortify
  FORTIFY_PROJECT: "10716"
  FORTIFY_BUILD_ID: "agents-apigee"

  # Whitesource
  WS_PROJECT_ID: "agents-apigee"
  WS_CONFIG_FILE: "whitesource.config"
  WS_BRANCH: main

include:
  - project: "apigov/beano_cicd"
    ref: master
    # the order of these include files is important
    file:
      - "/gitlabci/csrjobs.yml"
  - project: 'scurity/gitlabci'
    ref: master
    file:
      - '/.gitlab-ci-prepcsr.yml'
      - '/.gitlab-ci-fortify.yml'
      - "/.gitlab-ci-whitesource.yml"
      - "/.gitlab-ci-csr.yml"

stages:
  - security-scans
  - security-review

####################
# CSR - overridden from csrjobs.yml to effectively not see this job ever
####################
.dummy:
  stage: security-scans
  only:
    - xxxxx
  script:
    - ""

fetch-iriusrisk:
  extends: .dummy

twistlock:
  extends: .dummy
  # For some reason, twistlock always wants to run on branch pipelines unless this "only" section is here
  only:
    refs:
      - xxxxx

twistlock:on-schedule:
  extends: .dummy

twistlock-master:
  extends: .dummy

run-csr:
  dependencies:
    - fetch-fortify
    - whitesource

update-csr:
  dependencies:
    - fetch-fortify
    - whitesource:on-schedule
