image: docker:dind

variables:
  PROJECT: 'agents-apigee'
  CSR_SUPPRESSION_LIST: "/tmp/csr-suppressions/amplify-central/golang-agents-common.json"
  
  # Fortify
  FORTIFY_PROJECT: "10716"
  FORTIFY_BUILD_ID: "agents-apigee"

  # Whitesource
  WS_PROJECT_ID: "agents-apigee"
  WS_CONFIG_FILE: "whitesource.config"
  WS_BRANCH: main

  GIT_TAG_PREFIX: v

include:
  - project: 'scurity/gitlabci'
    ref: master
    file:
      - '/.gitlab-ci-prepcsr.yml'
      - '/.gitlab-ci-fortify.yml'
      - "/.gitlab-ci-twistlock.yml"
      - "/.gitlab-ci-iriusrisk.yml"
      - "/.gitlab-ci-whitesource.yml"
      - "/.gitlab-ci-csr.yml"
  - project: "apigov/beano_cicd"
    ref: master
    # the order of these include files is important
    file:
      - "/gitlabci/csrjobs.yml"

stages:
  - security-scans
  - security-review

.get-latest-tag: &get-latest-tag |
  if [ $(git --version | grep -Eo '2.*') ]; then 
    export LATEST_TAG=$(git tag -l --sort="version:refname" | grep -Eo '[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,3}$' | tail -1)
  else 
    export LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
  fi

twistlock-discovery:
  extends: .twistlock
  before_script:
    - echo "$PWD"
    - echo "$CI_PROJECT_DIR"
    - apk --no-cache update && apk add make
    - cd discovery && make docker-build 
    - export IMAGE_NAME=apigee-discovery-agent:latest
    - cd ..
  except:
    refs:
      - schedules
      - tags
      - main

twistlock-traceability:
  extends: .twistlock
  before_script:
    - echo "$PWD"
    - apk --no-cache update && apk add make
    - cd traceability && make docker-build 
    - export IMAGE_NAME=apigee-traceability-agent:latest
    - cd ..
  except:
    refs:
      - schedules
      - tags
      - main

twistlock-discovery:on-schedule:
  extends: .twistlock
  dependencies: []
  before_script:
    - apk --no-cache update && apk add git
    - *get-latest-tag
    - export IMAGE_NAME=ghcr.io/axway/apigee_discovery_agent:${GIT_TAG_PREFIX}${LATEST_TAG}
    - docker pull ${IMAGE_NAME}
  only:
    refs:
      - schedules

twistlock-traceability:on-schedule:
  extends: .twistlock
  dependencies: []
  before_script:
    - apk --no-cache update && apk add git
    - *get-latest-tag
    - export IMAGE_NAME=ghcr.io/axway/apigee_traceability_agent:${GIT_TAG_PREFIX}${LATEST_TAG}
    - docker pull ${IMAGE_NAME}
  only:
    refs:
      - schedules

whitesource:on-schedule:
  extends: .whitesource
  before_script:
    - git config --global http.sslVerify false
    - git config --global url."ssh://git@git.ecd.axway.org".insteadOf "https://git.ecd.axway.org"''
    - git fetch
    - *get-latest-tag
    - echo "Checking out ${GIT_TAG_PREFIX}${LATEST_TAG}"
    - git checkout ${GIT_TAG_PREFIX}${LATEST_TAG}

####################
# Override these from csrjobs.yml to effectively not ever run them. There's probably a better way to do this
# but I gave up trying
####################
fetch-iriusrisk:
  only:
    refs:
      - xxxxx
  except:
    refs:
      - yyyyy

twistlock:
  only:
    refs:
      - xxxxx
  except:
    refs:
      - yyyyy

twistlock:on-schedule:
  only:
    refs:
      - xxxxx
  except:
    refs:
      - yyyyy

twistlock-master:
  only:
    refs:
      - xxxxx
  except:
    refs:
      - yyyyy
