/*
 * Deployments
 *
 * Manage API proxy and shared flow deployments.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// ApiProxyRevisionDeploymentsServer struct for ApiProxyRevisionDeploymentsServer
type ApiProxyRevisionDeploymentsServer struct {
	Pod ApiProxyRevisionDeploymentsPod `json:"pod,omitempty"`
	// Deployment status.
	Status string `json:"status,omitempty"`
	// Pod type.
	Type []string `json:"type,omitempty"`
	// Server ID.
	UUID string `json:"uUID,omitempty"`
}
