/*
 * Environments API
 *
 * By default, Apigee organizations are provisioned with two environments: `test` and `prod`. An environment provides a runtime execution context for APIs. An API revision must be deployed to an environment before it can be accessed at runtime. No constraints are placed on the usage between different environments (`test` versus `prod`, for example). Developers are free to implement and enforce any type or testing, promotion, and deployment procedures that suit their development lifecycle.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// EnvironmentPropertiesProperty struct for EnvironmentPropertiesProperty
type EnvironmentPropertiesProperty struct {
	// Name of property.
	Name string `json:"name,omitempty"`
	// Set to `\"true\"` to enable or `\"false\"` to disable the property.
	Value string `json:"value,omitempty"`
}
