/*
 * Deployments
 *
 * Manage API proxy and shared flow deployments.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// ApiProxyRevisionDeploymentsConfiguration struct for ApiProxyRevisionDeploymentsConfiguration
type ApiProxyRevisionDeploymentsConfiguration struct {
	// Basepath of the API proxy revision.
	BasePath string   `json:"basePath,omitempty"`
	Steps    []string `json:"steps,omitempty"`
}
