/*
 * Deployments
 *
 * Manage API proxy and shared flow deployments.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// ApiProxyDeploymentsEnv API proxy deployments in an environment.
type ApiProxyDeploymentsEnv struct {
	// API proxy name and revision details.
	APIProxy []ApiProxyDeploymentsEnvAPiProxy `json:"aPIProxy,omitempty"`
	// Name of the API proxy.
	Name string `json:"name,omitempty"`
	// Name of the organization.
	Organization string `json:"organization,omitempty"`
}
