/*
 * API Proxies API
 *
 * Manage API proxies. You expose APIs on Apigee Edge by implementing API proxies.  API proxies decouple the app-facing API from your backend services, shielding those apps from backend code changes. As you make backend changes to your services, apps continue to call the same API without any interruption. For more information, see <a href=\"https://docs.apigee.com/api-platform/fundamentals/understanding-apis-and-api-proxies\">Understanding APIs and API proxies</a>.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// ApiProxyRevision API proxy revision.
type ApiProxyRevision struct {
	// Base URL of the API proxy.
	Basepaths            string                               `json:"basepaths,omitempty"`
	ConfigurationVersion ApiProxyRevisionConfigurationVersion `json:"configurationVersion,omitempty"`
	// Revision number, app name, and organization for the API proxy.
	ContextInfo string `json:"contextInfo,omitempty"`
	// Time when the API proxy revision was created in milliseconds since epoch.
	CreatedAt int32 `json:"createdAt,omitempty"`
	// Email address of developer that created the API proxy revision.
	CreatedBy string `json:"createdBy,omitempty"`
	// Description of the API proxy revision.
	Description string `json:"description,omitempty"`
	// Human-readable name of the API proxy.
	DisplayName                string                                     `json:"displayName,omitempty"`
	EntityMetaDataAsProperties ApiProxyRevisionEntityMetaDataAsProperties `json:"entityMetaDataAsProperties,omitempty"`
	// Time when the API proxy version was last modified in millisenconds since epoch.
	LastModifiedAt int32 `json:"lastModifiedAt,omitempty"`
	// Email address of developer that last modified the API proxy.
	LastModifiedBy string `json:"lastModifiedBy,omitempty"`
	// Manifest version.
	ManifestVersion string `json:"manifestVersion,omitempty"`
	// Name of the API proxy.
	Name string `json:"name"`
	// List of policies included in the API proxy revision.
	Policies []string `json:"policies,omitempty"`
	// List of API proxy names included in the API proxy revision.
	Proxies []string `json:"proxies,omitempty"`
	// List of the ProxyEndpoints in the `/proxies` directory. Typically, this element is included only when the API proxy was created using the Edge UI. This is a 'manifest' setting designed to provide visibility into the contents of the API proxy.
	ProxyEndpoints []string                      `json:"proxyEndpoints,omitempty"`
	ResourceFiles  ApiProxyRevisionResourceFiles `json:"resourceFiles,omitempty"`
	// List of resources included in the API proxy revision, formatted as `{type}://{name}`.
	Resources []string `json:"resources,omitempty"`
	// Revison of the API proxy.
	Revision string `json:"revision,omitempty"`
	// List of shared flows included in the API proxy revision.
	SharedFlows []string `json:"sharedFlows,omitempty"`
	// OpenAPI Specification that is associated with the API proxy. This value may be a URL or to a path in the spec store or on GitHub, for example.
	Spec interface{} `json:"spec,omitempty"`
	// List of TargetEndpoints in the `/targets` directory of the API proxy. Typically, this element is included only when the API proxy was created using the Edge  UI. This is a 'manifest' setting designed to provide visibility into the contents of the API proxy.
	TargetEndpoints []string `json:"targetEndpoints,omitempty"`
	// List of TargetServers referenced in any TargetEndpoints of the API proxy. Typically, this element is included only when the API proxy was created using the Edge  UI. This is a 'manifest' setting designed to provide visibility into the contents of the API proxy.
	TargetServers []string `json:"targetServers,omitempty"`
	// List of targets included in the API proxy revision.
	Targets []string `json:"targets,omitempty"`
	// Set to `Application`.
	Type string `json:"type,omitempty"`
}
