/*
 * Deployments
 *
 * Manage API proxy and shared flow deployments.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// ApiProxyRevisionDeploymentsPod Pod details.
type ApiProxyRevisionDeploymentsPod struct {
	// Pod name.
	Name string `json:"name,omitempty"`
	// Pod region.
	Region string `json:"region,omitempty"`
}
