/*
 * Deployments
 *
 * Manage API proxy and shared flow deployments.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// ApiProxyDeploymentDetailsEnv API proxy deployment details in an environment.
type ApiProxyDeploymentDetailsEnv struct {
	// Name of the environment.
	Environment string `json:"environment,omitempty"`
	// Revision details.
	Revision []ApiProxyRevisionDeploymentsEnvironment `json:"revision,omitempty"`
	// Name of the API proxy.
	Name string `json:"name,omitempty"`
	// Name of the organization.
	Organization string `json:"organization,omitempty"`
}
