/*
 * Shared flows and flow hooks API
 *
 * Manage shared flows and flow hooks. For more information, see: * <a href=\"https://docs.apigee.com/api-platform/fundamentals/shared-flows\">Reusable shared flows</a> * <a href=\"https://docs.apigee.com/api-platform/fundamentals/flow-hooks\">Attaching a shared flow using a flow hook</a>.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// SharedFlowRevision Shared flow revision.
type SharedFlowRevision struct {
	// Base paths for the shared flow.
	Basepaths            []string                               `json:"basepaths,omitempty"`
	ConfigurationVersion SharedFlowRevisionConfigurationVersion `json:"configurationVersion,omitempty"`
	// Revision number, app name, and organization for the shared flow.
	ContextInfo string `json:"contextInfo,omitempty"`
	// Time when the shared flow revision was created in milliseconds since epoch.
	CreatedAt int32 `json:"createdAt,omitempty"`
	// Email address of developer that created the shared flow.
	CreatedBy string `json:"createdBy,omitempty"`
	// Description of the shared flow.
	Description string `json:"description,omitempty"`
	// Display name for the shared flow.
	DisplayName                string                                       `json:"displayName,omitempty"`
	EntityMetaDataAsProperties SharedFlowRevisionEntityMetaDataAsProperties `json:"entityMetaDataAsProperties,omitempty"`
	// Time when the shared flow version was last modified in milliseconds since epoch.
	LastModifiedAt int32 `json:"lastModifiedAt,omitempty"`
	// Email address of developer that last modified the shared flow.
	LastModifiedBy string `json:"lastModifiedBy,omitempty"`
	// Manifest version of the bundle.
	ManifestVersion string `json:"manifestVersion,omitempty"`
	// Name of the shared flow.
	Name string `json:"name,omitempty"`
	// List of policies included in the shared flow revision.
	Policies []string `json:"policies,omitempty"`
	// List of API proxy names included in the shared flow revision.
	Proxies       []string                        `json:"proxies,omitempty"`
	ResourceFiles SharedFlowRevisionResourceFiles `json:"resourceFiles,omitempty"`
	// List of resources included in the shared flow revision, formatted as `{type}://{name}`.
	Resources []string `json:"resources,omitempty"`
	// List of shared flows included in the shared flow revision.
	SharedFlows []string `json:"sharedFlows,omitempty"`
	// OpenAPI Specification that is associated with the shared flow. This value may be a URL or to a path in the spec store or on GitHub, for example.
	Spec interface{} `json:"spec,omitempty"`
	// List of TargetServers referenced in any TargetEndpoints of the shared flow. Typically, this element is included only when the shared flow was created using the Edge  UI. This is a 'manifest' setting designed to provide visibility into the contents of the shared flow.
	TargetServers []string `json:"targetServers,omitempty"`
	// List of targets included in the shared flow revision.
	Targets []string `json:"targets,omitempty"`
	// Set to `Application`.
	Type string `json:"type,omitempty"`
}
