/*
 * Shared flows and flow hooks API
 *
 * Manage shared flows and flow hooks. For more information, see: * <a href=\"https://docs.apigee.com/api-platform/fundamentals/shared-flows\">Reusable shared flows</a> * <a href=\"https://docs.apigee.com/api-platform/fundamentals/flow-hooks\">Attaching a shared flow using a flow hook</a>.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// SharedFlowRevisionResourceFilesResourceFile Resource filename.
type SharedFlowRevisionResourceFilesResourceFile struct {
	// Name of the resource file.
	Name string `json:"name,omitempty"`
	// Type of resource file.
	Type string `json:"type,omitempty"`
}
