/*
 * Developer apps API
 *
 * Manage developers that register apps.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// DeveloperAppCredentials struct for DeveloperAppCredentials
type DeveloperAppCredentials struct {
	// Name and status of API products associated with the app.
	ApiProducts []ApiProductRef `json:"apiProducts,omitempty"`
	// List of attributes.
	Attributes []Attribute `json:"attributes,omitempty"`
	// Consumer API key.
	ConsumerKey string `json:"consumerKey,omitempty"`
	// Consumer secret.
	ConsumerSecret string `json:"consumerSecret,omitempty"`
	// Time the credentials expire in milliseconds since epoch.
	ExpiresAt int32 `json:"expiresAt,omitempty"`
	// Time the credentials were issued in milliseconds since epoch.
	IssuedAt int32 `json:"issuedAt,omitempty"`
	// OAuth scopes.
	Scopes []string `json:"scopes,omitempty"`
	// Status of the credentials.
	Status string `json:"status,omitempty"`
}
