/*
 * Environments API
 *
 * By default, Apigee organizations are provisioned with two environments: `test` and `prod`. An environment provides a runtime execution context for APIs. An API revision must be deployed to an environment before it can be accessed at runtime. No constraints are placed on the usage between different environments (`test` versus `prod`, for example). Developers are free to implement and enforce any type or testing, promotion, and deployment procedures that suit their development lifecycle.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Environment Environment details.
type Environment struct {
	// Output only. Time the environment was created in milliseconds since epoch.
	CreatedAt int `json:"createdAt,omitempty"`
	// Output only. Email address of the admin that created the environment.
	CreatedBy string `json:"createdBy,omitempty"`
	// Description of the environment.
	Description string `json:"description,omitempty"`
	// Output only. Time the environment was last modified in milliseconds since epoch.
	LastModifiedAt int `json:"lastModifiedAt,omitempty"`
	// Output only. Email of admin that last modified the environment.
	LastModifiedBy string `json:"lastModifiedBy,omitempty"`
	// Name of the environment. Valid characters include: `a-zA-Z0-9._\\-$ %`.
	Name       string                `json:"name"`
	Properties EnvironmentProperties `json:"properties,omitempty"`
}
