/*
 * Shared flows and flow hooks API
 *
 * Manage shared flows and flow hooks. For more information, see: * <a href=\"https://docs.apigee.com/api-platform/fundamentals/shared-flows\">Reusable shared flows</a> * <a href=\"https://docs.apigee.com/api-platform/fundamentals/flow-hooks\">Attaching a shared flow using a flow hook</a>.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// FlowHook Flow hook attachment details.
type FlowHook struct {
	// Flag that specifies whether execution should continue if the flow hook throws an exception.
	ContinueOnError string `json:"continueOnError,omitempty"`
	// Shared flow attached to the flow hook. Omitted if no shared flow is attached.
	SharedFlow string `json:"sharedFlow,omitempty"`
	// Displays the updated deployment status of the flow hook, such as `deployed` or `undeployed`. Only displays when attaching to or detaching from a flow hook.
	State string `json:"state,omitempty"`
}
