/*
 * Shared flows and flow hooks API
 *
 * Manage shared flows and flow hooks. For more information, see: * <a href=\"https://docs.apigee.com/api-platform/fundamentals/shared-flows\">Reusable shared flows</a> * <a href=\"https://docs.apigee.com/api-platform/fundamentals/flow-hooks\">Attaching a shared flow using a flow hook</a>.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// SharedFlowRevisionConfigurationVersion Version of the shared flow configuration schema to which this shared flow conforms. This setting may be used in the future to track the evolution of the shared flow format.
type SharedFlowRevisionConfigurationVersion struct {
	// Major version of the shared flow configuration schema. The only supported value is '4'.
	MajorVersion int32 `json:"majorVersion,omitempty"`
	// Minor version of the shared flow configuration schema. The only supported value is '0'.
	MinorVersion int32 `json:"minorVersion,omitempty"`
}
