/*
 * Deployments
 *
 * Manage API proxy and shared flow deployments.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// ApiProxyDeploymentsEnvAPiProxy struct for ApiProxyDeploymentsEnvAPiProxy
type ApiProxyDeploymentsEnvAPiProxy struct {
	// Name of the API proxy.
	Name string `json:"name,omitempty"`
	// Revision details.
	Revision []ApiProxyRevisionDeploymentDetailsEnvironment `json:"revision,omitempty"`
}
