/*
 * Developer apps API
 *
 * Manage developers that register apps.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// ApiProductRef API product information.
type ApiProductRef struct {
	// Name of API product.
	Apiproduct string `json:"apiproduct,omitempty"`
	// Status of API product.
	Status string `json:"status,omitempty"`
}
