/*
 * API Proxies API
 *
 * Manage API proxies. You expose APIs on Apigee Edge by implementing API proxies.  API proxies decouple the app-facing API from your backend services, shielding those apps from backend code changes. As you make backend changes to your services, apps continue to call the same API without any interruption. For more information, see <a href=\"https://docs.apigee.com/api-platform/fundamentals/understanding-apis-and-api-proxies\">Understanding APIs and API proxies</a>.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// ApiProxyRevisionConfigurationVersion Version of the API proxy configuration schema to which this API proxy conforms. This setting may be used in the future to track the evolution of the API proxy format.
type ApiProxyRevisionConfigurationVersion struct {
	// Major version of the API proxy configuration schema. The only supported value is '4'.
	MajorVersion int32 `json:"majorVersion,omitempty"`
	// Minor version of the API proxy configuration schema. The only supported value is '0'.
	MinorVersion int32 `json:"minorVersion,omitempty"`
}
