/*
 * Virtual hosts API
 *
 * Manage virtual hosts. Virtual hosts let multiple domain names connect to the same host. A virtual host on Edge defines the domains and ports on which an API proxy is exposed, and, by extension, the URL that apps use to access an API proxy. A virtual host also defines whether the API proxy is accessed by using the HTTP protocol, or by the encrypted HTTPS protocol.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// VirtualHostProperties **Edge Cloud and for Private Cloud 4.17.01 and later.**  List of properties.
type VirtualHostProperties struct {
	// Property name and value. For a list of valid properties, see  <a href=\"https://docs.apigee.com/api-platform/fundamentals/virtual-host-property-reference#virtualhostconfigurationproperties\">Virtual host configuration properties</a>.
	Property []VirtualHostPropertiesProperty `json:"Property,omitempty"`
}
