/*
 * Shared flows and flow hooks API
 *
 * Manage shared flows and flow hooks. For more information, see: * <a href=\"https://docs.apigee.com/api-platform/fundamentals/shared-flows\">Reusable shared flows</a> * <a href=\"https://docs.apigee.com/api-platform/fundamentals/flow-hooks\">Attaching a shared flow using a flow hook</a>.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// SharedFlow Shared flow metadata and revisions.
type SharedFlow struct {
	Metadata SharedFlowMetadata `json:"metadata,omitempty"`
	// Name of the shared flow.
	Name string `json:"name,omitempty"`
	// Revisions defined for the shared flow.
	Revision []string `json:"revision,omitempty"`
}
