/*
 * Developer apps API
 *
 * Manage developers that register apps.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Attribute Developer app attribute name and value.
type Attribute struct {
	// Name of attribute.
	Name string `json:"name,omitempty"`
	// Value of attribute.
	Value string `json:"value,omitempty"`
}
