/*
 * Developers API
 *
 * Developers must register with an organization on Apigee Edge. After they are registered, developers register their apps, choose the APIs they want to use, and receive the unique API credentials (consumer keys and secrets) needed to access your APIs.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Developer Developer details.
type Developer struct {
	// Output only. List of apps associated with the developer.
	Apps []string `json:"apps,omitempty"`
	// List of attributes that can be used to extend the default developer profile. With Apigee Edge for Public Cloud, the custom attribute limit is 18.
	Attributes []Attribute `json:"attributes,omitempty"`
	// Output only. List of companies associated with the developer.
	Companies []string `json:"companies,omitempty"`
	// Output only. Time the developer was created in milliseconds since epoch.
	CreatedAt int `json:"createdAt,omitempty"`
	// Output only. Email address of the developer that created the developer.
	CreatedBy string `json:"createdBy,omitempty"`
	// ID of the developer. Generated internally by Apigee and not guaranteed to stay consistent over time.
	DeveloperId string `json:"developerId,omitempty"`
	// Email address of the developer. This value is used to uniquely identify the developer in Apigee Edge.
	Email string `json:"email,omitempty"`
	// First name of the developer.
	FirstName string `json:"firstName,omitempty"`
	// Last name of the developer.
	LastName string `json:"lastName,omitempty"`
	// Output only. Last modified time as milliseconds since epoch.
	LastModifiedAt int `json:"lastModifiedAt,omitempty"`
	// Output only. Email of developer that last modified the app.
	LastModifiedBy string `json:"lastModifiedBy,omitempty"`
	// Output only. Name of the organization associated with the developer.
	OrganizationName string `json:"organizationName,omitempty"`
	// Status of the developer. Valid values are `active` and `inactive`.
	Status interface{} `json:"status,omitempty"`
	// Username. Not used by Apigee.
	UserName string `json:"userName,omitempty"`
}
