/*
 * Stats API
 *
 * Access metrics collected by Apigee Edge that measure API consumption and performance that are used to build Analytics reports.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// MetricsValues struct for MetricsValues
type MetricsValues struct {
	// Timestamp in millieseconds since epoch.
	Timestamp string `json:"timestamp,omitempty"`
	// Value of metric.
	Value string `json:"value,omitempty"`
}
