/*
 * API Proxies API
 *
 * Manage API proxies. You expose APIs on Apigee Edge by implementing API proxies.  API proxies decouple the app-facing API from your backend services, shielding those apps from backend code changes. As you make backend changes to your services, apps continue to call the same API without any interruption. For more information, see <a href=\"https://docs.apigee.com/api-platform/fundamentals/understanding-apis-and-api-proxies\">Understanding APIs and API proxies</a>.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// ApiProxyRequest API proxy request.
type ApiProxyRequest struct {
	// Name of the API proxy. Restrict the characters used to: `A-Za-z0-9._-`
	Name string `json:"name"`
}
