/*
 * Policies API
 *
 * Apigee Edge out-of-the-box policies augment your APIs to control traffic,enhance performance, enforce security, and increase the utility of your APIs, without requiring you to write any code or modify any backend services. In addition, Apigee provides extension policies that let you implement custom logic in the form of JavaScript, Python, Java, and XSLT stylesheets.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Policy Policy details. Descriptions of common policy elements and attributes are provided below. For information about the complete set of elements available for each policy type, see <a href=\"https://docs.apigee.com/api-platform/reference/policies/reference-overview-policy\">Policy reference overview</a>.
type Policy struct {
	// This attribute is deprecated.
	Async string `json:"async,omitempty"`
	// Flag that specifies whether to continue flow execution even after the policy fails. Set to `true` to continue flow execution. Defaults to `false`.
	ContinueOnError string `json:"continueOnError,omitempty"`
	// Display name used to label the policy in the Edge UI proxy editor with a different, natural-language name.
	DisplayName string `json:"DisplayName,omitempty"`
	// Flag that specifies whether the policy is enabled. Set to `false` to \"turn off\" the policy. Defaults to `true`.
	Enabled string `json:"enabled,omitempty"`
	// Internal name of the policy. The value of the name attribute can contain letters, numbers, spaces, hyphens, underscores, and periods. This value cannot exceed 255 characters. Optionally, set `DisplayName` to label the policy in the Edge UI proxy editor with a different, natural-language name.
	Name string `json:"name,omitempty"`
}
