/*
 * Deployments
 *
 * Manage API proxy and shared flow deployments.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// ApiProxyDeploymentsOrgEnvironment struct for ApiProxyDeploymentsOrgEnvironment
type ApiProxyDeploymentsOrgEnvironment struct {
	// API proxy name and revision details.
	APIProxy []ApiProxyDeploymentsEnvAPiProxy `json:"aPIProxy,omitempty"`
	// Name of the environment.
	Name string `json:"name,omitempty"`
}
