/*
 * Developer apps API
 *
 * Manage developers that register apps.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Attributes Developer app attributes.
type Attributes struct {
	Attribute []Attribute `json:"attribute,omitempty"`
}
