/*
 * Stats API
 *
 * Access metrics collected by Apigee Edge that measure API consumption and performance that are used to build Analytics reports.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Metrics Metric details.
type Metrics struct {
	// Environment details.
	Environments []MetricsEnvironments `json:"environments,omitempty"`
}
