name: Release Apigee Agents

on:
  workflow_run:
    workflows: [Build Apigee Discovery Agent, Discovery Agent Docker, Build Apigee Traceability Agent, Traceability Agent Docker]:
    types: [completed]

jobs:
  notifyTeamsChannel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Notify Teams channel
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          TAG: ${{ github.ref_name }}
        run: ./release.sh
