name: Release Apigee Agents

on:
  push:
    branches: [ '**' ]
    # tags:
    #   - "*"

jobs:
  buildDiscoveryAgent:
    env:
      GOFLAGS: "-mod=mod"
      GOWORK: "off"
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/discovery
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build discovery agent
        working-directory: discovery
        run: |
          git rev-parse --short HEAD > commit_id
          echo "${{ github.ref }}" > version
          make build

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: discovery/bin/apigee_discovery_agent
          asset_name: apigee_discovery_agent
          tag: ${{ github.ref }}
          overwrite: true
          body: "Apigee Discovery Agent - ${{ github.ref }}"

  buildTraceabilityAgent:
    env:
      GOFLAGS: "-mod=mod"
      GOWORK: "off"
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/traceability
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build traceability agent
        working-directory: traceability
        run: |
          git rev-parse --short HEAD > commit_id
          echo "${{ github.ref }}" > version
          make build

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: traceability/bin/apigee_traceability_agent
          asset_name: apigee_traceability_agent
          tag: ${{ github.ref }}
          overwrite: true
          body: "Apigee Traceability Agent - ${{ github.ref }}"

      - name: Upload release yaml
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: traceability/apigee_traceability_agent.yml
          asset_name: apigee_traceability_agent.yml
          tag: ${{ github.ref }}
          overwrite: true
          body: "Apigee Traceability Agent YAML - ${{ github.ref }}"

  notifyTeamsChannel:
    env:
      TEAMS_WEBHOOK_URL: "https://axwaysoftware.webhook.office.com/webhookb2/e859058b-5110-40a3-871e-7641a739e06a@300f59df-78e6-436f-9b27-b64973e34f7d/IncomingWebhook/cb060241bae943b2bfb6dab32d61a99d/d1ae36f4-0132-4a9c-943d-3541201d7aa3"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Notify Teams channel
        # run: ./release.sh ${{ github.ref }}
        run: ./release.sh 0.1.4
