name: Build Apigee Traceability Agent

on:
  push:
    branches: [main, "APIGOV-*"]
  pull_request:
    branches: [main]

jobs:
  testTraceabilityAgent:
    env:
      GOFLAGS: "-mod=mod"
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/discovery
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test traceability agent
        working-directory: traceability
        run: go test -v ./...

  buildTraceabilityAgent:
    env:
      GOFLAGS: "-mod=mod"
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/traceability
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build traceability agent
        working-directory: traceability
        run: make build

      - uses: actions/upload-artifact@v2
        with:
          name: apigee_traceability_agent
          path: traceability/bin/apigee_traceability_agent

      - uses: actions/upload-artifact@v2
        with:
          name: apigee_traceability_agent.yml
          path: traceability/apigee_traceability_agent.yml
