# This action is shared by workflows that want to run the unit tests
name: Test the discovery agent

on:
  workflow_call

jobs:
  testDiscoveryAgent:
    env:
      GOFLAGS: "-mod=mod"
      GOWORK: "off"
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/discovery
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
            go-version: 3

      - name: Test discovery agent
        working-directory: discovery
        run: make test
