# This action is shared by workflows that want to run the unit tests
name: Test the traceability agent

on:
  workflow_call

jobs:
  testTraceabilityAgent:
    env:
      GOFLAGS: "-mod=mod"
      GOWORK: "off"
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/traceability
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
            go-version: 1.21

      - name: Test traceability agent
        working-directory: traceability
        run: make test
